<?php

namespace AppBundle\Repository;

/**
 * MarketDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketDataRepository extends \Doctrine\ORM\EntityRepository
{
}
